# Generated by Django 5.2.9 on 2026-05-14 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0002_delete_usercompanyprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_normalized', models.TextField(blank=True, db_index=True, default='', editable=False, verbose_name='Search (normalized)')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='registry.company', verbose_name='Харьяалах компани')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Хэрэглэгчийн компани',
                'verbose_name_plural': 'Хэрэглэгчийн компаниуд',
                'db_table': 'registry_usercompanyprofile',
            },
        ),
    ]
