# Generated by Django 5.2.9 on 2026-05-14 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ADMIN_FULL', 'Бүрэн админ'), ('COMPANY_ADMIN', 'Компанийн админ'), ('COMPANY_OPERATOR', 'Компанийн оператор'), ('BRIGADE_LEADER', 'Бригадын ахлагч'), ('VIEWER', 'Зөвхөн харах')], max_length=32, unique=True, verbose_name='Кодлол')),
                ('name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('description', models.TextField(blank=True, default='', verbose_name='Тайлбар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
            ],
            options={
                'verbose_name': 'Үүрэг',
                'verbose_name_plural': 'Үүргүүд',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Олгосон огноо')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.company', verbose_name='Компанийн scope (хоосон = бүх компани)')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_roles', to=settings.AUTH_USER_MODEL, verbose_name='Олгосон хэрэглэгч')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to='accounts.role', verbose_name='Үүрэг')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Хэрэглэгчийн үүрэг',
                'verbose_name_plural': 'Хэрэглэгчийн үүргүүд',
                'ordering': ('-granted_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'role', 'company'), name='uniq_user_role_company')],
            },
        ),
    ]
