# Generated by Django 5.2.9 on 2026-05-14 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='БНБ Систем', max_length=100, verbose_name='Илгээгчийн нэр')),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Илгээгчийн Email')),
                ('sender_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Илгээгчийн утас')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP сервер')),
                ('email_port', models.IntegerField(default=587, verbose_name='SMTP порт')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='TLS ашиглах')),
                ('email_host_user', models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP хэрэглэгч (email)')),
                ('email_host_password', models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP нууц үг / App Password')),
                ('sms_gateway_url', models.CharField(blank=True, default='', max_length=500, verbose_name='SMS Gateway URL')),
                ('sms_gateway_token', models.CharField(blank=True, default='', max_length=500, verbose_name='SMS Gateway Token')),
                ('sms_sender_name', models.CharField(default='BNB', max_length=50, verbose_name='SMS илгээгчийн нэр')),
                ('telegram_bot_token', models.CharField(blank=True, default='', max_length=300, verbose_name='Telegram Bot Token')),
                ('facebook_page_token', models.CharField(blank=True, default='', max_length=500, verbose_name='Facebook Page Access Token')),
                ('viber_auth_token', models.CharField(blank=True, default='', max_length=300, verbose_name='Viber Auth Token')),
                ('site_name', models.CharField(default='Барилгачдын нэгдсэн мэдээллийн бааз', max_length=100, verbose_name='Сайтын нэр')),
                ('site_phone', models.CharField(blank=True, default='', max_length=100, verbose_name='Сайтын утас')),
                ('site_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Сайтын email')),
                ('site_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Хаяг')),
                ('site_facebook', models.CharField(blank=True, default='', max_length=300, verbose_name='Facebook хуудас URL')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
            ],
            options={
                'verbose_name': 'Системийн тохиргоо',
                'verbose_name_plural': 'Системийн тохиргоо',
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS (Утас)'), ('telegram', 'Telegram'), ('facebook', 'Facebook Messenger'), ('viber', 'Viber')], max_length=20, verbose_name='Суваг')),
                ('target_type', models.CharField(choices=[('all_companies', 'Бүх компани'), ('all_workers', 'Бүх ажиллагсад'), ('all_brigades', 'Бүх бригад'), ('selected', 'Сонгосон')], default='selected', max_length=30, verbose_name='Хүлээн авагч төрөл')),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Хүлээн авагчийн нэр')),
                ('recipient_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Хүлээн авагчийн хаяг/дугаар')),
                ('subject', models.CharField(blank=True, default='', max_length=300, verbose_name='Гарчиг')),
                ('body', models.TextField(verbose_name='Мессежийн агуулга')),
                ('status', models.CharField(choices=[('sent', 'Илгээсэн'), ('failed', 'Амжилтгүй'), ('pending', 'Хүлээгдэж байна')], default='pending', max_length=10, verbose_name='Төлөв')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Алдааны мессеж')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Илгээсэн огноо')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Илгээсэн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Мессежийн бүртгэл',
                'verbose_name_plural': 'Мессежийн бүртгэлүүд',
                'ordering': ('-created_at',),
            },
        ),
    ]
