# Generated by Django 5.2.9 on 2026-05-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCompanyProfile',
        ),
    ]
