# Generated by Django 5.2.9 on 2026-05-14 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_normalized', models.TextField(blank=True, db_index=True, default='', editable=False, verbose_name='Search (normalized)')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Нэр/тайлбар')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Зураг (File)')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Зургийн URL')),
                ('link_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Дарахад орох холбоос (URL)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Эрэмбэ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннерууд',
                'db_table': 'registry_banner',
                'ordering': ('-is_active', 'sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Гарчиг')),
                ('subtitle', models.TextField(blank=True, default='', verbose_name='Дэд гарчиг / тайлбар')),
                ('media_type', models.CharField(choices=[('image', 'Зураг'), ('video', 'Видео')], default='image', max_length=10, verbose_name='Медиа төрөл')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Зураг (upload)')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Зургийн URL')),
                ('video', models.FileField(blank=True, null=True, upload_to='hero_video/', verbose_name='Видео (upload)')),
                ('video_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Видео URL (YouTube/MP4)')),
                ('btn1_text', models.CharField(blank=True, default='', max_length=100, verbose_name='Товч 1 текст')),
                ('btn1_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Товч 1 холбоос')),
                ('btn2_text', models.CharField(blank=True, default='', max_length=100, verbose_name='Товч 2 текст')),
                ('btn2_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Товч 2 холбоос')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Эрэмбэ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
            ],
            options={
                'verbose_name': 'Hero баннер (зүүн 1/3 зураг/видео)',
                'verbose_name_plural': 'Hero баннерууд (зүүн 1/3 зураг/видео)',
                'db_table': 'registry_herobanner',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SliderAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Гарчиг')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='Богино тайлбар')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_ads/', verbose_name='Зураг (upload)')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Зургийн URL')),
                ('link_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Холбоос (дарахад орох)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Эрэмбэ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
            ],
            options={
                'verbose_name': 'Урсдаг зар',
                'verbose_name_plural': 'Урсдаг зарууд',
                'db_table': 'registry_sliderad',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SubBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Нэр/тайлбар')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sub_banners/', verbose_name='Зураг (upload)')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Зургийн URL')),
                ('link_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Холбоос (дарахад орох)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Эрэмбэ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
            ],
            options={
                'verbose_name': 'Дэд баннер (баруун дээд хэсэг)',
                'verbose_name_plural': 'Дэд баннерууд (баруун дээд хэсэг)',
                'db_table': 'registry_subbanner',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PublicPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_normalized', models.TextField(blank=True, db_index=True, default='', editable=False, verbose_name='Search (normalized)')),
                ('title', models.CharField(max_length=200, verbose_name='Гарчиг')),
                ('body', models.TextField(blank=True, default='', verbose_name='Агуулга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүссэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('is_published', models.BooleanField(default=True, verbose_name='Нийтлэх эсэх')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_posts', to=settings.AUTH_USER_MODEL, verbose_name='Нийтэлсэн хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Нээлттэй пост',
                'verbose_name_plural': 'Нээлттэй постууд',
                'db_table': 'registry_publicpost',
                'ordering': ('-created_at',),
            },
        ),
    ]
