# Generated by Django 5.2.9 on 2026-05-19 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('house', 'Орон сууц & Барилга'), ('material', 'Материал & Тоног'), ('worker', 'Ажилтан & Бригад'), ('repair', 'Засвар & Үйлчилгээ'), ('design', 'Зураг төсөл'), ('other', 'Бусад')], default='other', max_length=20, verbose_name='Ангилал')),
                ('title', models.CharField(max_length=200, verbose_name='Гарчиг')),
                ('description', models.TextField(blank=True, default='', verbose_name='Тайлбар')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Үнэ')),
                ('price_type', models.CharField(choices=[('mnt', '₮ (Төгрөг)'), ('usd', '$ (Доллар)'), ('negotiable', 'Тохиролцоно'), ('free', 'Үнэгүй')], default='negotiable', max_length=20, verbose_name='Үнийн төрөл')),
                ('city', models.CharField(blank=True, default='UB', max_length=8, verbose_name='Хот/Аймаг')),
                ('district', models.CharField(blank=True, default='', max_length=8, verbose_name='Дүүрэг/Сум')),
                ('contact_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Холбоо барих нэр')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Утас')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='И-мэйл')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Зураг 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Зураг 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Зураг 3')),
                ('status', models.CharField(choices=[('active', 'Идэвхтэй'), ('inactive', 'Идэвхгүй'), ('pending', 'Хүлээгдэж байна')], default='active', max_length=20, verbose_name='Төлөв')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Үзсэн тоо')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дуусах огноо')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Оруулсан хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Зар',
                'verbose_name_plural': 'Зарууд',
                'db_table': 'public_ad',
                'ordering': ('-created_at',),
            },
        ),
    ]
