# Generated by Django 5.2.9 on 2026-05-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Тендерийн нэр')),
                ('organization', models.CharField(blank=True, default='', max_length=300, verbose_name='Захиалагч')),
                ('price', models.CharField(blank=True, default='', max_length=100, verbose_name='Үнэ')),
                ('deadline', models.CharField(blank=True, default='', max_length=20, verbose_name='Хугацаа')),
                ('method', models.CharField(blank=True, default='', max_length=200, verbose_name='ХАА журам')),
                ('tender_code', models.CharField(blank=True, default='', max_length=100, verbose_name='Тендерийн дугаар')),
                ('url', models.URLField(blank=True, default='', max_length=500, verbose_name='Холбоос')),
                ('is_construction', models.BooleanField(default=False, verbose_name='Барилгатай холбоотой')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Нэмсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендерүүд',
                'db_table': 'public_tender',
                'ordering': ('-created_at',),
            },
        ),
    ]
