# Generated by Django 5.2.9 on 2026-05-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='category',
            field=models.CharField(blank=True, choices=[('construction', 'Барилга угсралт'), ('repair', 'Засвар'), ('design', 'Зураг төсөл'), ('road', 'Зам, гүүр'), ('engineering', 'Инженерийн шугам'), ('material', 'Материал'), ('equipment', 'Тоног төхөөрөмж'), ('consulting', 'Зөвлөх'), ('service', 'Үйлчилгээ'), ('other', 'Бусад')], default='other', max_length=50, verbose_name='Ангилал'),
        ),
    ]
