# Generated by Django 5.2.9 on 2026-05-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_tender_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='material_item',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Материалын дэд ангилал'),
        ),
        migrations.AddField(
            model_name='ad',
            name='material_subcategory',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Материалын үндсэн ангилал'),
        ),
        migrations.AddField(
            model_name='ad',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('ton', '₮ / тонн'), ('piece', '₮ / ш'), ('m2', '₮ / м²'), ('m3', '₮ / м³'), ('kg', '₮ / кг'), ('meter', '₮ / м'), ('negotiable', 'Тохиролцоно')], default='', max_length=20, verbose_name='Үнийн нэгж'),
        ),
    ]
