# Generated by Django 5.2.9 on 2026-05-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_ad_material_item_ad_material_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='house_location',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Байршил (дүүрэг/аймаг)'),
        ),
        migrations.AddField(
            model_name='ad',
            name='house_location_type',
            field=models.CharField(blank=True, choices=[('ub', 'Улаанбаатар'), ('province', 'Орон нутаг')], default='', max_length=10, verbose_name='Байршлын төрөл'),
        ),
        migrations.AddField(
            model_name='ad',
            name='house_rooms',
            field=models.CharField(blank=True, choices=[('r1', '1 өрөө'), ('r2', '2 өрөө'), ('r3', '3 өрөө'), ('r3plus', '3-аас дээш өрөө'), ('duplex', 'Дуплекс'), ('studio', 'Студи')], default='', max_length=20, verbose_name='Өрөөний тоо'),
        ),
        migrations.AddField(
            model_name='ad',
            name='house_type',
            field=models.CharField(blank=True, choices=[('sale', 'Зарна'), ('rent', 'Түрээслэнэ'), ('buy', 'Худалдаж авна'), ('rent_partial', 'Хэсэгчлэн түрээслэнэ')], default='', max_length=20, verbose_name='Зарын төрөл'),
        ),
    ]
