# Generated by Django 5.2.9 on 2026-05-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_ad_house_location_ad_house_location_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('material', 'Материал'), ('equipment', 'Тоног төхөөрөмж'), ('rental', 'Түрээс'), ('realestate', 'Үл хөдлөх хөрөнгө'), ('service', 'Барилгын үйлчилгээ'), ('design', 'Зураг төсөв, дизайн'), ('worker', 'Ажилтан, ажлын зар'), ('tender', 'Тендер, төсөл'), ('company', 'Компаниуд'), ('other', 'Бусад')], default='other', max_length=20, verbose_name='Ангилал'),
        ),
    ]
