# Generated by Django 5.2.9 on 2026-06-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_alter_ad_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cement', 'Цемент, шохой'), ('sand_gravel', 'Элс, хайрга, дайрга'), ('brick_block', 'Тоосго, блок'), ('rebar_metal', 'Арматур, төмөр'), ('wood', 'Модон материал'), ('roof', 'Дээврийн материал'), ('insulation', 'Дулаалга'), ('window_door', 'Цонх, хаалга'), ('interior', 'Дотор засал'), ('plumbing', 'Сантехник'), ('electrical', 'Цахилгаан'), ('labor', 'Ажилчдын хөлс'), ('transport', 'Тээвэр'), ('other', 'Бусад')], max_length=30, verbose_name='Ангилал')),
                ('name', models.CharField(max_length=200, verbose_name='Материалын нэр')),
                ('unit', models.CharField(max_length=30, verbose_name='Нэгж')),
                ('price_min', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Доод үнэ')),
                ('price_max', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Дээд үнэ')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='Тайлбар')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
            ],
            options={
                'verbose_name': 'Материалын үнэ',
                'verbose_name_plural': 'Материалын үнэнүүд',
                'ordering': ('category', 'name'),
            },
        ),
    ]
