# Generated by Django 5.2.9 on 2026-06-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_materialprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialprice',
            name='category',
            field=models.CharField(choices=[('mat_cement', '1. Материал — Цемент, шохой'), ('mat_sand', '1. Материал — Элс, хайрга, дайрга'), ('mat_brick', '1. Материал — Тоосго, блок'), ('mat_rebar', '1. Материал — Арматур, төмөр'), ('mat_wood', '1. Материал — Модон материал'), ('mat_roof', '1. Материал — Дээврийн материал'), ('mat_insulation', '1. Материал — Дулаалга'), ('mat_window', '1. Материал — Цонх, хаалга'), ('mat_interior', '1. Материал — Дотор засал'), ('mat_plumbing', '1. Материал — Сантехник'), ('mat_electrical', '1. Материал — Цахилгаан'), ('mat_other', '1. Материал — Бусад материал'), ('labor_general', '2. Цалин — Барилгачин'), ('labor_special', '2. Цалин — Мэргэжилтэн'), ('labor_engineer', '2. Цалин — Инженер, хяналт'), ('transport_material', '3. Тээвэр — Материал тээвэр'), ('transport_waste', '3. Тээвэр — Хог зайлуулах'), ('transport_other', '3. Тээвэр — Бусад тээвэр'), ('machine_crane', '4. Машин механизм — Кран'), ('machine_excavator', '4. Машин механизм — Экскаватор'), ('machine_concrete', '4. Машин механизм — Бетон зуурагч'), ('machine_other', '4. Машин механизм — Бусад машин'), ('other_design', '5. Бусад — Зураг төсөл'), ('other_vat', '5. Бусад — НӨАТ'), ('other_permit', '5. Бусад — Зөвшөөрөл, бүртгэл'), ('other_insurance', '5. Бусад — Даатгал'), ('other_misc', '5. Бусад — Бусад')], max_length=30, verbose_name='Ангилал'),
        ),
    ]
