# Generated by Django 5.2.9 on 2026-06-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_alter_materialprice_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(choices=[('low_rise', 'Амины орон сууц (1-2 давхар)'), ('mid_rise', 'Олон айлын орон сууц (3-9 давхар)'), ('high_rise', 'Өндөр давхар (10+ давхар)'), ('office', 'Оффисын барилга'), ('warehouse', 'Агуулах'), ('other', 'Бусад')], max_length=20, verbose_name='Барилгын төрөл')),
                ('work_type', models.CharField(choices=[('foundation', 'Суурь'), ('wall', 'Хана'), ('insulation', 'Дулаалга'), ('slab', 'Хучилт'), ('roof', 'Дээвэр'), ('floor', 'Шал'), ('interior', 'Дотор засал'), ('window', 'Цонх, хаалга'), ('engineering', 'Инженерийн систем'), ('labor', 'Ажилчид'), ('other', 'Бусад')], max_length=20, verbose_name='Ажлын төрөл')),
                ('material_name', models.CharField(max_length=200, verbose_name='Материалын нэр')),
                ('norm_per_m2', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='1м²-д орох норм')),
                ('unit', models.CharField(max_length=20, verbose_name='Нэгж')),
                ('db_category', models.CharField(blank=True, max_length=50, verbose_name='DB ангилал')),
                ('db_name_contains', models.CharField(blank=True, max_length=100, verbose_name='DB нэр хайх')),
                ('notes', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
            ],
            options={
                'verbose_name': 'Материалын норм',
                'verbose_name_plural': 'Материалын нормууд',
                'ordering': ['building_type', 'work_type'],
            },
        ),
    ]
