# Generated by Django 5.2.9 on 2026-06-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_materialnorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='open_date',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Нээгдэх огноо'),
        ),
    ]
